// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAys7m3K23-uzXpcqUBOLo2jKhLQjpU8UM',
    appId: '1:316872733832:web:5ee95db1ed1d09891f9b3d',
    messagingSenderId: '316872733832',
    projectId: 'bookverse-eaadb',
    authDomain: 'bookverse-eaadb.firebaseapp.com',
    storageBucket: 'bookverse-eaadb.firebasestorage.app',
    measurementId: 'G-4EGMMRXH6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt3P5Ydl-5CNUrmTGTaxXJWOniGqFBOxs',
    appId: '1:316872733832:android:ee07fc0cec1bbcf81f9b3d',
    messagingSenderId: '316872733832',
    projectId: 'bookverse-eaadb',
    storageBucket: 'bookverse-eaadb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwKSyrHJxHt76xBfyUx70F0RlPgpTZ2JQ',
    appId: '1:316872733832:ios:2b64c4cae02716d31f9b3d',
    messagingSenderId: '316872733832',
    projectId: 'bookverse-eaadb',
    storageBucket: 'bookverse-eaadb.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwKSyrHJxHt76xBfyUx70F0RlPgpTZ2JQ',
    appId: '1:316872733832:ios:2b64c4cae02716d31f9b3d',
    messagingSenderId: '316872733832',
    projectId: 'bookverse-eaadb',
    storageBucket: 'bookverse-eaadb.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAys7m3K23-uzXpcqUBOLo2jKhLQjpU8UM',
    appId: '1:316872733832:web:63433d0f2a82a1fa1f9b3d',
    messagingSenderId: '316872733832',
    projectId: 'bookverse-eaadb',
    authDomain: 'bookverse-eaadb.firebaseapp.com',
    storageBucket: 'bookverse-eaadb.firebasestorage.app',
    measurementId: 'G-3PXJ8QR7H7',
  );

}